SELECT MAX(SALARY) FROM EMPLOYEE WHERE SALARY NOT IN (SELECT MAX(SALARY) FROM EMPLOYEE);
SELECT DEPTID, MAX(SALARY) FROM EMPLOYEE GROUP BY DEPTID;
SELECT E.NAME, M.NAME FROM EMPLOYEE E, EMPLOYEE M WHERE E.MGR_ID = E.EMP_ID;.
SELECT * FROM EMPLOYEE WHERE SUBSTRING(CONVERT(VARCHAR,JOINING_DATE,103),7,4)='2013';
SELECT * FROM EMPLOYEE WHERE SUBSTRING(CONVERT(VARCHAR,JOINING_DATE,100),1,3)='Jan';
SELECT DEPARTMENT, SUM(SALARY) TOTAL_SALARY FROM EMPLOYEE GROUP BY DEPARTMENT ORDER BY TOTAL_SALARY DESC;
SELECT DEPARTMENT, COUNT(FIRST_NAME), SUM(SALARY) TOTAL_SALARY FROM EMPLOYEE GROUP BY DEPARTMENT ORDER BY TOTAL_SALARY DESC;
SELECT DEPARTMENT, AVG(SALARY) AVGSALARY FROM EMPLOYEE GROUP BY DEPARTMENT ORDER BY AVGSALARY ASC;
SELECT DEPARTMENT, MAX(SALARY) MAXSALARY FROM EMPLOYEE GROUP BY DEPARTMENT ORDER BY MAXSALARY ASC;
SELECT DEPARTMENT, MIN(SALARY) MINSALARY FROM EMPLOYEE GROUP BY DEPARTMENT ORDER BY MINSALARY ASC;
SELECT FIRST_NAME, INCENTIVE_AMOUNT FROM EMPLOYEE A INNER JOIN INCENTIVES B ON A.EMPLOYEE_ID = B.EMPLOYEE_REF_ID AND INCENTIVE_AMOUNT>3000;
ALTER TABLE EMPLOYEE DROP CONSTRAINT EMPLOYEE_PK;
ALTER TABLE EMPLOYEE DROP CONSTRAINT EMPLOYEE_FK;
SELECT * FROM EMPLOYEE WHERE ENAME LIKE 'S_____';
SELECT * FROM EMPLOYEE WHERE ENAME LIKE '%R';
SELECT * FROM EMP1 UNION SELECT * FROM EMP2;
SELECT * FROM EMP1 INTERSECT SELECT * FROM EMP2;
SELECT * FROM EMP1 MINUS SELECT * FROM EMP2;
SELECT FIRST_NAME+'_'+LAST_NAME FROM EMPLOYEE;
SELECT * FROM EMPLOYEE WHERE FIRST_NAME LIKE '%O%';
SELECT * FROM EMPLOYEE WHERE FIRST_NAME LIKE '___n';

